name: cargo-test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: pushd cybergarage && cargo build --verbose && popd
    - name: Run tests
      run: pushd cybergarage && cargo test --verbose -- --test-threads=1 && popd
